#!/usr/bin/env python3
"""Install a rendered suite as THE task instance.

Wiring a new render used to be a manual copy of ground_truth.json plus a hand-edited oracle, which
is easy to get half-right: a stale oracle answer scores the new key and looks like a scorer bug.
This does all of it from one source of truth (the suite's ground_truth.json + race.mp4) and prints
what changed.

  install_instance.py <suite_dir> [--url <materials-url>]

<suite_dir> is a run_suite.sh output directory. Writes:
  steps/solve/tests/ground_truth.json   the key
  steps/solve/solution/solve.sh         the oracle, regenerated from that key
  environment/Dockerfile                MATERIALS_SHA256 (and MATERIALS_URL with --url)
  task.toml                             the advertised runtime in the metadata comment
"""
import argparse
import hashlib
import json
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
TASK = HERE.parent


def sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def render_oracle(gt):
    """The oracle answer: every scored field, each race tagged with the MIDPOINT of its window.

    The judge matches a reported race to a GT race by time within +/-15 s, so the midpoint is the
    most forgiving anchor an honest answer can use.
    """
    races = []
    for r in gt["races"]:
        races.append({
            "track": r["track"],
            "t": round((r["t_start"] + r["t_end"]) / 2, 1),
            "items_collected": r["items_collected"],
            "spinouts": r["spinouts"],
            "skid_time": r["skid_time"],
        })
    body = json.dumps({"races": races}, indent=2)
    return '''#!/bin/bash
# Oracle: hero (tux) per-race counts + skid_time (VIDEO seconds), each tagged with its video time t.
# GENERATED by generator/install_instance.py from the suite's ground_truth.json -- do not hand-edit,
# regenerate it, or the oracle and the key drift apart.
set -euo pipefail
# Write where the verifier reads it (tests/test.sh: judge.py --solution /workspace/output/solution.json)
# and where the agent prompt tells the agent to write. SOLUTION_PATH overrides only for local tests.
OUT="${SOLUTION_PATH:-/workspace/output/solution.json}"
mkdir -p "$(dirname "$OUT")"
cat > "$OUT" <<'JSON'
''' + body + '''
JSON
'''


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("suite_dir")
    ap.add_argument("--url", help="materials URL to pin in the Dockerfile")
    args = ap.parse_args()

    suite = Path(args.suite_dir)
    gt = json.loads((suite / "ground_truth.json").read_text())
    mp4 = suite / "race.mp4"
    digest = sha256(mp4)
    runtime_min = max(r["t_end"] for r in gt["races"]) / 60.0

    key = TASK / "steps/solve/tests/ground_truth.json"
    key.write_text(json.dumps(gt, indent=1) + "\n")
    print("wrote %s (%d races)" % (key.relative_to(TASK), len(gt["races"])))

    oracle = TASK / "steps/solve/solution/solve.sh"
    oracle.write_text(render_oracle(gt))
    oracle.chmod(0o755)
    print("wrote %s" % oracle.relative_to(TASK))

    dockerfile = TASK / "environment/Dockerfile"
    text = dockerfile.read_text()
    text, n = re.subn(r"(ARG MATERIALS_SHA256=)[0-9a-f]{64}", r"\g<1>" + digest, text)
    assert n == 1, "MATERIALS_SHA256 not found in the Dockerfile"
    if args.url:
        text, n = re.subn(r"(ARG MATERIALS_URL=)\S+", lambda m: m.group(1) + args.url, text)
        assert n == 1, "MATERIALS_URL not found in the Dockerfile"
        print("pinned MATERIALS_URL")
    dockerfile.write_text(text)
    print("pinned MATERIALS_SHA256=%s" % digest)

    toml = TASK / "task.toml"
    text = toml.read_text()
    text, n = re.subn(r"\(~\d+(?:\.\d+)?\s*min total\)", "(~%.0f min total)" % runtime_min, text)
    toml.write_text(text)
    print("task.toml runtime -> ~%.0f min (%d substitutions)" % (runtime_min, n))
    print("\nscored values now in force:")
    for r in gt["races"]:
        print("  %-22s items %2d  skid %7.2fs" % (r["track"], r["items_collected"], r["skid_time"]))


if __name__ == "__main__":
    main()
